CREATE TABLE IF NOT EXISTS onboard_requests (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  current_floor INTEGER NOT NULL,
  dropoff_floor INTEGER NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
